### ISSUE TITLE
how to add auto Focus (question)

### ISSUE THREAD

**Issue by jasan-s** [zakangelle/react-password-mask#22]

**Comment by zakangelle** [comment]
@jasan-s Right now there's no way to pass HTML attributes as props to the `input` field, which is definitely not ideal. I've been thinking about ways to handle this without just doing `...this.props` on the `input` field. I'll come up with something this week so you can pass an `autoFocus` prop.

**Comment by zakangelle** [comment]
`autoFocus` prop has been added in v3.1.0 - also added a `maxLength` prop.
